name: Chrome Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    - run: npm ci
    - run: node ./e2e/run.js
